/*
 * Calculator API
 *
 * REST API for performing arithmetic operations using JWT and custom headers
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Swashbuckle.AspNetCore.Annotations;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using CalculatorApi.Services.Interfaces;
using CalculatorApi.Models;
using CalculatorApi.Attributes;

namespace CalculatorApi.Controllers
{
    /// <summary>
    /// Controller for handling arithmetic operations: add, subtract, multiply, divide.
    /// </summary>
    [ApiController]
    [Route("api/v1/[controller]")]
    [Authorize]
    public class CalculatorController : ControllerBase
    {
        private readonly ICalculatorService _calculatorService;
        private readonly ILogger<CalculatorController> _logger;

        public CalculatorController(ICalculatorService calculatorService, ILogger<CalculatorController> logger)
        {
            _calculatorService = calculatorService ?? throw new ArgumentNullException(nameof(calculatorService));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
        /// <summary>
        /// Performs a calculation on two numbers
        /// </summary>
        /// <param name="body"></param>
        /// <param name="xOperation">The arithmetic operation to perform</param>
        /// <response code="200">Calculation result</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="500">Internal Server Error</response>
        [HttpPost]
        [Route("calculate")]
        [ValidateModelState]
        [SwaggerOperation("Calculate")]
        [SwaggerResponse(statusCode: 200, type: typeof(CalculationResponse), description: "תוצאה של החישוב")]
        [SwaggerResponse(statusCode: 400, description: "בקשה שגויה")]
        [SwaggerResponse(statusCode: 401, description: "לא מאומת")]
        [SwaggerResponse(statusCode: 500, description: "שגיאה פנימית")]
        public async Task<IActionResult> Calculate(
            [FromBody][Required] CalculationRequest body,
            [FromHeader(Name = "X-Operation")][Required] string xOperation)
        {
            if (string.IsNullOrWhiteSpace(xOperation))
            {
                _logger.LogWarning("X-Operation header is missing or empty");
                return BadRequest(new { error = "X-Operation header is required." });
            }

            if (!Enum.TryParse<OperationType>(xOperation.ToLower(), true, out var operationType))
            {
                _logger.LogWarning("Invalid value for X-Operation header: {XOperation}", operationType);
                return BadRequest(new { error = $"Invalid value for X-Operation. Allowed values are: {string.Join(", ", Enum.GetNames(typeof(OperationType)))}." });
            }
            try
            {
                _logger.LogInformation("Calculating {Operation} with values: A={A}, B={B}", xOperation, body.FirstNumber, body.SecondNumber);
                var result = await _calculatorService.CalculateAsync(body, operationType);

                return Ok(result);
            }
            catch (ArgumentException ex)
            {
                _logger.LogWarning(ex, "Invalid calculation argument");
                return BadRequest(new { error = ex.Message });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unexpected error during calculation");
                return StatusCode(500, new { error = "Unexpected error occurred" });
            }
        }
    }
}
